name: dart_polylabel2
description: >-
  A fast algorithm for finding polygon pole of inaccessibility. 
  Useful for optimal placement of a text label on a polygon.
version: 1.0.0
repository: https://github.com/JaffaKetchup/dart_polylabel2
issue_tracker: https://github.com/JaffaKetchup/dart_polylabel2/issues

funding:
  - https://github.com/sponsors/JaffaKetchup

environment:
  sdk: ">=3.6.0 <4.0.0"

dependencies:
  collection: ^1.18.0
  meta: ^1.11.0

dev_dependencies:
  lints: ^6.0.0
  test: ^1.24.9
